### ISSUE TITLE
Error message opening xlsx file

### ISSUE THREAD

**Issue by tethysgeco** [3liz/qgis-wfsOutputExtension#13] opened 2020-04-01 08:10 UTC
Hi, we have installed the release 1.2.3 with Qgis server 3.4 and Lizmap WC 3.3.3.  
When we download xlsx files from the WebGIS and open them with MS Office 365, the error message in the image below is returned. It means that there is a problem with some part of the file content and if you think that the source is reliable Excel will try to restore it. 
If you click “yes” the file opens and everything seems ok.. but this message is a problem for users. Do you have any idea about the reason? Do you know if this can be fixed?  
![immagine](https://user-images.githubusercontent.com/23027624/78114029-e9d39100-7400-11ea-9184-ed042b8bf38e.png)

**Comment by MattiasSp** [comment] 2020-04-09 05:48
Chiming in to say that I get the same error on QGIS Server 3.10.2-2 with qgis-wfsOutputExtension 1.2.2. After restoring the file, Excel provides the following restoration report (my translation):
```xml
<?xml version="1.0" encoding="UTF-8" standalone="true"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <logFileName>error125160_01.xml</logFileName>
  <summary>Error encountered in the file C:\my\filename.xlsx</summary>
  <repairedRecords>
    <repairedRecord>Repaired records: Workbook properties from part of /xl/workbook.xml (Workbook)</repairedRecord>
  </repairedRecords>
</recoveryLog>
```

**Comment by rldhont** [comment] 2020-04-09 12:33
The xlsx is generated by QGIS classes, I think GDAL wrapper. Do you have the same issue if you do a Save As xlsx in QGIS Desktop ?

**Comment by tethysgeco** [comment] 2020-04-10 10:38
@rldhont , doing save as xlsx in Qgis desktop seems ok. 
No error message is shown opening from excel the exported file .
Comparing xlsx table of the same postgis layer (named segnalazioni) downloaded from Lizmap and exported from Qgis desktop I can see this column in version from Lizmap: 

gml_id
--
Segnalazioni.3
Segnalazioni.6
etc..

This column is absent in file exported from Qgis desktop. I don't know if it's a useful info

**Comment by tethysgeco** [comment] 2020-05-06 07:46
Attached you can find an example of the same table exported using lizmap (qgis server 3.4) and qgis desktop 3.4. Opening the lizmap export we have the error message mentioned above and then there is also an error in the recovered file:

![image](https://user-images.githubusercontent.com/23027624/81149328-4c7af800-8f7e-11ea-87db-c778d3c68299.png)


[export_test_excel_qgis.xlsx](https://github.com/3liz/qgis-wfsOutputExtension/files/4585363/export_test_excel_qgis.xlsx)
[export_test_excel_lizmap.xlsx](https://github.com/3liz/qgis-wfsOutputExtension/files/4585364/export_test_excel_lizmap.xlsx)

**Comment by Gustry** [comment] 2020-09-17 14:26
I will still have a look.
I just noticed this PR on qgis/qgis. I don't know if it's related, but just to keep track of it https://github.com/qgis/QGIS/pull/38837

**Comment by pcav** [comment] 2020-09-17 14:33
sounds right, thanks

**Comment by Gustry** [comment] 2020-09-28 12:04
The bug related to the Excel format should be fixed with the new version 1.4.0, please try again.

**Comment by tethysgeco** [comment] 2020-09-28 12:06
we'll try as soon as possible, thanks!

**Comment by tethysgeco** [comment] 2020-10-08 13:54
Hi,
we’ve tried version 1.4.1. 
Most of the exported tables are ok, error message is no more displayed by excel. 
The same message of the first post of this thread is still returned when we have a numeric field with zero values mixed with non-zero values, and the result is something like this:
![immagine](https://user-images.githubusercontent.com/23027624/95467830-3682c080-097e-11eb-92ba-5ac64ab7a0f7.png)



Conversely when there are special characters in text fields (e.g. < or &) in exported excel tables we find <![CDATA[<text]] but no error message is returned while opening xlsx file.

**Comment by Gustry** [comment] 2020-10-08 14:42
@tethysgeco 
FYI, we got a regression regarding 1.4.X.
It's not possible to export as shapefile. I'm on it.

**Comment by tethysgeco** [comment] 2020-10-09 06:50
ok, thanks

**Comment by Gustry** [comment] 2020-10-09 07:10
Version 1.5.0 has been released to fix the export of ZIP based formats.
Can you open separate issue ? This one for opening XLSX file seems fixed. We can look to the decimal separator.
For instance, CDATA would be another discussion because it seems the issue is upstream in QGIS : https://github.com/qgis/QGIS/blob/master/src/server/services/wfs/qgswfsgetfeature.cpp#L1550

**Closed by Gustry** 2020-10-09 07:10 UTC
Labels: bug, feedback
