### ISSUE TITLE
[CDATA[<text]] in exported xlsx tables

### ISSUE THREAD

**Issue by tethysgeco** [3liz/qgis-wfsOutputExtension#17] opened 2020-10-09 10:23 UTC
When there are special characters in text fields (e.g. < or &) in exported excel tables we find <![CDATA[<text]] (no error message is returned opening xlsx file).

**Comment by Gustry** [comment] 2020-10-09 11:12
It seems the issue is upstream in QGIS : https://github.com/qgis/QGIS/blob/master/src/server/services/wfs/qgswfsgetfeature.cpp#L1550
To fix this, either it would need a fix in QGIS Server, or search/replace (refactor field algo) after getting the GML.

**Comment by Gustry** [comment] 2022-03-18 10:28
This should be fixed in QGIS Server 3.24.1 and 3.22.6.

Thanks to @pcav for funding this bugfix.

**Closed by Gustry** 2022-03-18 10:28 UTC
Labels: enhancement
